### ISSUE TITLE
"configure" command fails in Ubuntu Linux

### ISSUE THREAD

**Issue by jgranick** [blackberry/SDL#14] opened 2012-03-08 04:30 UTC
I'm interested in using SDL to bring a cross-platform application framework over for the BlackBerry.

I have tried "build_for_playbook.sh" in two versions of Ubuntu (one 32-bit and one 64) just to make sure. In both installs, configure fails, saying that qcc cannot create executables.

Here is an example of the commands I am using:

source /opt/bbndk-2.0.0/bbndk-env.sh
./build_for_playbook.sh

Should I be doing something differently, or is this an issue with using Linux instead of OS X? (I don't have a Mac on hand at this moment). I'm just interested in compiling the current version as a dynamic library, so I can get one with making sure the framework runs properly for the device.

Thank you very much!

(Here is the full output off the terminal)

joshua@joshua-VirtualBox:~/Development/BlackBerry/SDL$ source /opt/bbndk-2.0.0/bbndk-env.sh 
joshua@joshua-VirtualBox:~/Development/BlackBerry/SDL$ ./build_for_playbook.sh 
checking for arm-unknown-nto-qnx6.5.0eabi-gcc... /opt/bbndk-2.0.0/host/linux/x86/usr/bin/qcc -V4.4.2,gcc_ntoarmv7le_cpp 
checking whether the C compiler works... no
configure: error: in `/home/joshua/Development/BlackBerry/SDL':
configure: error: C compiler cannot create executables
See`config.log' for more details
make: **\* No rule to make target `all'.  Stop.
Build Failed!
joshua@joshua-VirtualBox:~/Development/BlackBerry/SDL$

**Comment by jnicholl** [comment] 2012-03-08 04:43
I'm away at a conference at the moment, so I can't take a look. This should definitely work on Linux, so something's wrong somewhere... Can I see more of the failure log? 
Also, if you just need the library, you could import the project into the NDK instead and build it that way instead of from the command-line.

----- Original Message -----
From: Joshua Granick [mailto:reply@reply.github.com]
Sent: Wednesday, March 07, 2012 11:30 PM
To: Jeremy Nicholl
Subject: [SDL] "configure" command fails in Ubuntu Linux (#14)

I'm interested in using SDL to bring a cross-platform application framework over for the BlackBerry.

I have tried "build_for_playbook.sh" in two versions of Ubuntu (one 32-bit and one 64) just to make sure. In both installs, configure fails, saying that qcc cannot create executables.

Here is an example of the commands I am using:

source /opt/bbndk-2.0.0/bbndk-env.sh
./build_for_playbook.sh

Should I be doing something differently, or is this an issue with using Linux instead of OS X? (I don't have a Mac on hand at this moment). I'm just interested in compiling the current version as a dynamic library, so I can get one with making sure the framework runs properly for the device.

Thank you very much!

---

Reply to this email directly or view it on GitHub:
https://github.com/blackberry/SDL/issues/14

---

This transmission (including any attachments) may contain confidential information, privileged material (including material protected by the solicitor-client or other applicable privileges), or constitute non-public information. Any use of this information by anyone other than the intended recipient is prohibited. If you have received this transmission in error, please immediately reply to the sender and delete this information from your system. Use, dissemination, distribution, or reproduction of this transmission by unintended recipients is not authorized and may be unlawful.

**Comment by jgranick** [comment] 2012-03-08 05:06
Thanks! Are you at GDC?

I can look at building it from inside the NDK. Do you have any pointers of where I would copy the files, and what I would run to get the process started?

Here is the contents of my config.log file: http://pastie.org/3546232

**Comment by jnicholl** [comment] 2012-03-08 05:11
Yes, I'm at GDC.
There should already be a .project file in the repository. Just open up the ndk, go to File, Import, Existing Projects into Workspace, choose the directory and it should import and be able to build.

The problem in this case is that SDL actually depends on another library, TouchControlOverlay. You can check it out of github and import it into the ndk to build it. That's why the configure is currently failing.

----- Original Message -----

**Comment by jgranick** [comment] 2012-03-08 05:17
I had TouchControlOverlay checked out in a neighboring directory (~/Development/BlackBerry/TouchControlOverlay), but I guess it needed to be compiled first. I'll give it a shot with the IDE and see if I can build it

**Comment by jgranick** [comment] 2012-03-08 05:45
Great! Thank you :)

I didn't realize that the Native SDK came with an IDE. I'm not a big Eclipse fan, anyway, but with your instructions it was pretty easy to import both projects and compile them while running Windows.

Although I have what I need, you may also want to know that it did not work when I was in Linux. I was specifically using Ubuntu 11.04 32-bit. Here's the output in the console, while trying to compile TouchControlOverlay:

***\* Rebuild of configuration Device-Release for project TouchControlOverlay ****

***\* Internal Builder is used for build ****
Build error
String index out of range: -26

**Comment by jnicholl** [comment] 2012-03-08 06:10
We'll definitely look into that. Glad you got it working for now.

----- Original Message -----

**Comment by asimonov-im** [comment] 2012-03-12 21:30
I can't seem to reproduce the problem on Ubuntu. I don't have 11.04, but I've been using 11.10 32-bit without any problems. If you get the chance, can you re-clone the repository and try again?

**Comment by absmall** [comment] 2012-04-08 22:15
This is because build_for_playbook.sh hardcoded linking to TouchControlOverlay.so. This means TouchControlOverlay.so is required for everything, including the test whether the compiler works. If it is missing, it will fail with the above error.

I've just submitted a pull request that will make the failure print an error message saying TouchControlOverlay is not available, and gives the URL to download it, instead of this more confusing error message.

**Comment by asimonov-im** [comment] 2012-04-09 12:34
Thanks for the info, that makes sense. I had some questions about the pull request, so I haven't merged it yet.

**Comment by asimonov-im** [comment] 2012-06-07 14:45
I seem to have forgotten to close this. The pull request did get merged.

**Closed as completed by asimonov-im** 2012-06-07 14:45 UTC
